language: node_js
node_js:
# ISSUE with 'node' (v8.x.x). Need to fix. See https://github.com/Microsoft/napajs/issues/5
- 'node'
- '6'
- '4'
os:
# ISSUE with 'linux'. Need to fix. See https://github.com/Microsoft/napajs/issues/4
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

# should re-enable extra build in matrix after ISSUE 4 and 5 resolved
# matrix:
#   include:
#   - os: linux
#     compiler: g++-6
#     addons:
#       apt:
#         sources:
#         - ubuntu-toolchain-r-test
#         packages:
#         - g++-6
#     env:
#     - COMPILER_OVERRIDE="CXX=g++-6 CC=gcc-6"
#   - os: linux
#     compiler: clang
#     addons:
#       apt:
#         packages:
#         - clang-3.4
#     env:
#     - COMPILER_OVERRIDE="CC=clang-3.4 CXX=clang++-3.4"

before_install:
- |
  if [ $TRAVIS_OS_NAME == linux ]; then
    if [ "$COMPILER_OVERRIDE" == "" ]; then
      #use g++5 by default
      export CXX="g++-5" CC="gcc-5"
    else
      export ${COMPILER_OVERRIDE}
    fi
  fi
install:
- npm install cmake-js -g
- npm install
script:
- npm test
- npm run unittest
